<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success_page'] = array(
        'title' => 'Encrpytion Successful',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter the phrase you want to encrypt.'),
    );
    $form['direction'] = array(
        '#title' => 'direction',
        '#type' => 'textfield',
        '#description' => t('Left or right?.'),
    );

    $form['shift_value'] = array(
        '#title' => 'shift value',
        '#type' => 'textfield',
        '#description' => t('encoding value?.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'encode your phrase',
    );
    return $form;
}

function change_letter($letter, $direction, $shift_value, $dictionary) {

    //code is slightly redundant here but helps with readability
    if ($direction == "right") {
        $dictionary = $dictionary;
    } elseif ($direction == "left") {
        $dictionary = array_reverse($dictionary);
    }
    $dictionary_value = (array_search($letter, $dictionary)) + $shift_value;

    //if number is 26, number is actually 0 because of offset inherent to arrays
    if ($dictionary_value == 26) {
        $dictionary_value = 0;
    }
    //if number is bigger than 26
    if ($dictionary_value > 26) {
        $dictionary_value = $dictionary_value % 26;
    }
    $new_letter = $dictionary[$dictionary_value];
    return $new_letter;
}

function cipher_form_submit($form, &$form_state) {
    $phrase = $form_state['values']['phrase'];
    $direction = $form_state['values']['direction'];
    $shift_value = $form_state['values']['shift_value'];
    $dictionary = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    $phrase = str_split(strtolower($phrase));
    $result = array();

    for ($i = 0; $i <= count($phrase) ; $i++) {
        if ((in_array($phrase[$i], $dictionary))) {
            $new_letter = change_letter($phrase[$i], $direction, $shift_value, $dictionary);
            array_push($result, $new_letter);
        } else {
            array_push($result, $phrase[$i]);
        }
    }

    $result = join($result);

    // echo '<pre>';
    // var_dump($result);
    // echo '</pre>';
    // exit;

    $_SESSION['encoded_phrase'] = $result;
    $form_state['redirect'] = 'cipher_success_page';

}

function cipher_success() {
    $final = $_SESSION['encoded_phrase'];
    return $final;
}
